name: Package

on:
  push:
    branches: [main]

jobs:
  faracster-gui:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build
        run: docker build -f $GITHUB_WORKSPACE/Dockerfile -t ghcr.io/farcaster-project/faracster-gui/app:latest $GITHUB_WORKSPACE

      - name: Docker push to GitHub Packages
        run: docker push ghcr.io/farcaster-project/faracster-gui/app:latest
